apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-webapp
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: prod
        values:
          branch: main
  template:
    metadata:
      name: "{{name}}-simple-webapp"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      sources:
        - repoURL: https://github.com/marcobejarano/Implementing-GitOps-with-Kubernetes.git
          targetRevision: "{{values.branch}}"
          path: ./simple-webapp
      destination:
        name: "{{name}}"
        namespace: "argocd"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          
# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
  # name: simple-webapp
  # namespace: argocd
# spec:
  # generators:
    # - list:
        # elements:
          # - name: in-cluster
            # branch: main
  # template:
    # metadata:
      # name: "{{name}}-simple-webapp"
    # spec:
      # project: default
      # sources:
        # - repoURL: https://github.com/marcobejarano/Implementing-GitOps-with-Kubernetes.git
          # targetRevision: "{{branch}}"
          # path: ./simple-webapp
      # destination:
        # server: https://kubernetes.default.svc
        # namespace: "argocd"
      # syncPolicy:
        # automated:
          # prune: false
          # selfHeal: true
        # syncOptions:
          # - CreateNamespace=true
